env:
  - HUGO_VERSION="0.50"
  - HUGO_VERSION="0.51"
  - HUGO_VERSION="0.52"
  - HUGO_VERSION="0.53"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - hugo version
  - gem install html-proofer
  - git clone https://github.com/gohugoio/hugoBasicExample.git

script:
  - cd hugoBasicExample
  - hugo -t tale-hugo --themesDir ../..
  - htmlproofer public --check-html --disable-external --allow-hash-href
