env:
  - HUGO_VERSION="0.50"
  - HUGO_VERSION="0.74.3"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - hugo version
  - gem install html-proofer
  - htmlproofer --version
  - git clone https://github.com/EmielH/hugo-theme-test.git

script:
  - cd hugo-theme-test
  - hugo -t tale-hugo --themesDir ../..
  - htmlproofer public --check-html --disable-external --allow-hash-href --checks-to-ignore LinkCheck
