install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.51_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
  - git clone https://github.com/gohugoio/hugoBasicExample.git
  - cd hugoBasicExample
  - git submodule add -f https://github.com/EmielH/tale-hugo.git themes/tale
  - sudo apt-get install -y tree
  - tree

script:
  - hugo -t tale
  - tree
